---
# https://github.com/Shopify/erb-lint#linters
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: false
  SelfClosingTag:
    enabled: true
    enforced_style: 'always'
  Rubocop:
    enabled: false
